[workspace]
members = [
  "dct-safe",
  "dct-safe/meta",
  "multi-transfer-dct",
  "multi-transfer-dct/meta",
  "multisig",
  "multisig/meta",
  "bridged-tokens-wrapper",
  "bridged-tokens-wrapper/meta"
]
